all:
	gcc -Wall -Wextra -Werror -c ft_bzero.c ft_calloc.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c
	mv ft_bzero.o ft_calloc.o ft_memchr.o ft_memcmp.o ft_memcpy.o ft_memmove.o ft_memset.o ../../obj
