all:
	gcc -Wall -Wextra -Werror -c ft_i_putchar_fd.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c
	mv ft_i_putchar_fd.o ft_putchar_fd.o ft_putendl_fd.o ft_putnbr_fd.o ft_putstr_fd.o ../../obj
