all:
	gcc -Wall -Wextra -Werror -c ft_atoi.c ft_itoa.c ft_tolower.c ft_toupper.c ft_to_lowercase.c ft_to_uppercase.c ft_uitoa_base.c ft_ulltoa_base.c
	mv ft_atoi.o ft_itoa.o ft_tolower.o ft_toupper.o ft_to_lowercase.o ft_to_uppercase.o ft_uitoa_base.o ft_ulltoa_base.o ../../obj
